Repository ucsb-cs156-w22/team04-w22-6pm-HappyCows, pull requests merged in 2022-03, with the labels that each got.

#30 jc - Add parameters to Commons type.
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-6pm-4, 10

#34 rd - create commons storybook page
  frontend/src/stories/pages/Commons/CommonsCreatePage.stories.js
Labels: w22-6pm-4

#25 en - New Login Page + some reworks
  frontend/src/App.js
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsCard.js
  frontend/src/main/components/Commons/CommonsList.js
  frontend/src/main/pages/HomePage.js
  frontend/src/main/pages/LoginPage.js
  frontend/src/main/utils/useBackend.js
  frontend/src/stories/pages/LoginPage.stories.js
  frontend/src/tests/components/Commons/CommonsList.test.js
  frontend/src/tests/pages/LoginPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
Labels: w22-6pm-4, Merge-Candidate

#46 add heroku links to `README.md`
  README.md
Labels: w22-6pm-4

#26 add coverage to `UserCommons.java`
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: w22-6pm-4, Merge-Candidate

#29 CommonsController coverage -> 100%
  src/main/java/edu/ucsb/cs156/happiercows/repositories/CommonsRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-6pm-4, Merge-Candidate

#38 rd - add milkPrice + startDate to commonsFixtures + ISO date format
  frontend/src/fixtures/commonsFixtures.js
Labels: w22-6pm-4, Merge-Candidate

#39 jc - Add HTTP PUT for the `Commons` type.
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-6pm-4, Merge-Candidate

#42 Market Cow Price and Number of Cows
  frontend/src/fixtures/userCommonsFixtures.js
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/pages/PlayPage.js
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: 10, w22-6pm-3

#40 jk- create listPage
  frontend/src/App.js
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/components/Commons/CreateCommonsForm.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/OurTable.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminListCommonPage.js
  frontend/src/main/utils/commonsUtils.js
  frontend/src/stories/components/Commons/CommonsTable.stories.js
  frontend/src/stories/pages/AdminListCommonPage.stories.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/components/Commons/CreateCommonsForm.test.js
  frontend/src/tests/components/OurTable.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminListCommonsPage.test.js
  frontend/src/tests/utils/commonsUtil.test.js
Labels: w22-6pm-4, 10

#44 implement "delete a commons" functionality in `commonsController.java`
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/UserCommonsRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: w22-6pm-4, 10

#43 w22-6pm-3 Profits
  frontend/package-lock.json
  frontend/src/fixtures/profitsFixtures.js
  frontend/src/fixtures/profitsTableFixtures.js
  frontend/src/main/components/Commons/Profits.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Commons/Profits.test.js
  frontend/src/tests/components/Commons/ProfitsTable.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/ProfitsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Profit.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/ProfitRepository.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/ProfitsControllerTests.java
Labels: 10, 20, w22-6pm-3

#54 w22-6pm-3 Adding images and background picture to Play Page UI
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/pages/PlayPage.js
Labels: w22-6pm-3, Attn-peer-CR, Merge-Candidate

#56 W22-6pm-3 Success toast shows correct information when creating a new commons
  frontend/src/main/pages/AdminCreateCommonsPage.js
Labels: 10, w22-6pm-3, Merge-Candidate

#62 Simple Frontend changes
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/pages/PlayPage.js
Labels: w22-6pm-3

#63 Buy and Sell endpoints with tests
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/UserCommons.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: w22-6pm-3

#64 Fixing joining a commons and respective controller tests
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UserCommonsControllerTests.java
Labels: w22-6pm-3
